k10:
  externalGateway:
    create: true
  auth:
    tokenAuth:
      enabled: false
    basicAuth:
      enabled: true
      htpasswd: k10admin:$2y$05$2ao4JP8w7far.N5CBApovuBSKnkG0Z6AYdCBnCJZC6VaTqY8SWBYS
